const homeData = [
  {
    id: 1,
    url: "https://www.pexels.com/photo/beige-bungalow-house-259588/",
    noOfRooms: 4,
    noOfBathrooms: 3,
    noOfToilets: 4,
    price: "₦500,000",
    title: "Semi Detached Duplex",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    location: "Ikeja, Lagos",
  },
  {
    id: 2,
    url: "src/components/Landing-page/images/HouseImage.avif",
    noOfRooms: 2,
    noOfBathrooms: 3,
    noOfToilets: 2,
    price: "₦250,000",
    title: "Off Shore BQ",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.  ",
    location: "Lekki, Lagos",
  },

  {
    id: 3,
    url: "src/components/Landing-page/images/HouseImage.avif",
    noOfRooms: 7,
    noOfBathrooms: 6,
    noOfToilets: 8,
    price: "₦1.3M",
    title: "Mansion",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.  ",
    location: "Banana Island, Lagos",
  },
  {
    id: 4,
    url: "https://www.pexels.com/photo/house-2581922/",
    noOfRooms: 2,
    noOfBathrooms: 2,
    noOfToilets: 2,
    price: "₦800,000",
    title: "Apartment Complex",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    location: "Victoria Island, Lagos",
  },
  {
    id: 5,
    url: "https://www.pexels.com/photo/house-2581922/",
    noOfRooms: 2,
    noOfBathrooms: 2,
    noOfToilets: 2,
    price: "₦800,000",
    title: "Apartment Complex",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    location: "Victoria Island, Lagos",
  },
  {
    id: 6,
    url: "https://www.pexels.com/photo/house-2581922/",
    noOfRooms: 2,
    noOfBathrooms: 2,
    noOfToilets: 2,
    price: "₦800,000",
    title: "Apartment Complex",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    location: "Victoria Island, Lagos",
  },
  {
    id: 7,
    url: "https://www.pexels.com/photo/house-2581922/",
    noOfRooms: 2,
    noOfBathrooms: 2,
    noOfToilets: 2,
    price: "₦800,000",
    title: "Apartment Complex",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    location: "Victoria Island, Lagos",
  },
  {
    id: 8,
    url: "https://www.pexels.com/photo/house-2581922/",
    noOfRooms: 2,
    noOfBathrooms: 2,
    noOfToilets: 2,
    price: "₦800,000",
    title: "Apartment Complex",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    location: "Victoria Island, Lagos",
  },
];

export default homeData;
